"""add diabetes_type to users

Revision ID: 5ae27d433e39
Revises: 9545a68382b4
Create Date: 2025-09-18 14:33:20.332955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae27d433e39'
down_revision = '9545a68382b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diabetes_type', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('diabetes_type')

    # ### end Alembic commands ###
