"""add bmi fields and reading context

Revision ID: 9545a68382b4
Revises: 4b6a870f82e2
Create Date: 2025-09-18 13:50:18.323860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9545a68382b4'
down_revision = '4b6a870f82e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('height_cm')

    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_column('context')

    # ### end Alembic commands ###
